---
# - hosts: all
#   name: Include dynamic variables
#   become: yes
#   tasks:
#     - include_tasks: ../dynamic-assignments/env-vars.yml
#       tags:
#         - always

# - import_playbook: ../static-assignments/common.yml

# - import_playbook: ../static-assignments/uat-webservers.yml

# - import_playbook: ../static-assignments/loadbalancers.yml

# - import_playbook: ../static-assignments/db-servers.yml

- hosts: all
  tasks:
    - name: Import common.yml playbook
      import_playbook: ../static-assignments/common-del.yml
